<RockSimDocument>
 <FileVersion>2</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name>Caliber ISP</Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <FixedCd2>0.78</FixedCd2>
   <FixedCd3>0.8</FixedCd3>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>5</CPCalcFlags>
   <LaunchGuideLength>914.4</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments><![CDATA[your basic 3.1" x 60" 4FNC 54mm blaster]]></Comments>
   <Designer>LOC Precision</Designer>
   <CPSimFlags>1</CPSimFlags>
   <LastSerialNumber>15</LastSerialNumber>
   <DisplayFlags>1</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,1196.21687066967,0.,0.</BarromanXN>
   <BarrowmanCNa>0.,13.0139318828242,0.,0.</BarrowmanCNa>
   <RockSimXN>0.,1239.19966834715,0.,0.</RockSimXN>
   <RockSimCNa>0.,16.7388559572565,0.,0.</RockSimCNa>
   <ViewType>0</ViewType>
   <ViewStageCount>1</ViewStageCount>
   <ViewTypeEdit>0</ViewTypeEdit>
   <ViewStageCountEdit>1</ViewStageCountEdit>
   <ZoomFactor>0.</ZoomFactor>
   <ZoomFactorEdit>0.</ZoomFactorEdit>
   <ScrollPosX>0</ScrollPosX>
   <ScrollPosY>0</ScrollPosY>
   <ScrollPosXEdit>0</ScrollPosXEdit>
   <ScrollPosYEdit>0</ScrollPosYEdit>
   <ThreeDFlags>0</ThreeDFlags>
   <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
   <SimulationEventList>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>LOC Precision</PartMfg>
     <KnownMass>134.</KnownMass>
     <Density>1049.2093265</Density>
     <Material>Polystyrene PS</Material>
     <Name>Nose cone</Name>
     <KnownCG>190.5</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>234.085654037564</CalcMass>
     <CalcCG>238.068946482777</CalcCG>
     <WettedSurface>4.76581015685776e-002</WettedSurface>
     <PaintedSurface>4.76581015685776e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC PNC-3.00</PartNo>
     <PartDesc>Plastic nose cone</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>0</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.13252603548293</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.13252603548293</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <Len>285.75</Len>
     <BaseDia>78.74</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>1</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>95.25</ShoulderLen>
     <WallThickness>3.175</WallThickness>
     <ShapeParameter>0.</ShapeParameter>
     <ShoulderOD>75.565</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>LOC/Precision</PartMfg>
     <KnownMass>93.</KnownMass>
     <Density>1121.29241</Density>
     <Material>Paper</Material>
     <Name>payload section airframe tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>123.244567304348</CalcMass>
     <CalcCG>177.8</CalcCG>
     <WettedSurface>8.79644183828114e-002</WettedSurface>
     <PaintedSurface>8.79644183828114e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC BT-3.00</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>8</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>78.74</OD>
     <ID>76.2</ID>
     <Len>355.6</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>40.</KnownMass>
       <Density>1121.29241</Density>
       <Material>paper</Material>
       <Name>section coupler</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>-76.2</Xb>
       <CalcMass>35.9429647925305</CalcMass>
       <CalcCG>76.2</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>TC-3.00</PartNo>
       <PartDesc>Tube Coupler</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>3</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>76.2</OD>
       <ID>74.422</ID>
       <Len>152.4</Len>
       <FinishCode>3</FinishCode>
       <UsageCode>4</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (LOC)</Material>
       <Name>Bulkhead</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>-73.025</Xb>
       <CalcMass>20.9946646226804</CalcMass>
       <CalcCG>3.175</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>4</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>76.2</OD>
       <ID>0.</ID>
       <Len>6.35</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>1</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <MassObject>
       <PartMfg>Custom</PartMfg>
       <KnownMass>32.</KnownMass>
       <Density>0.</Density>
       <Material></Material>
       <Name>eyebolt, washers, nut</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>431.8</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>12</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>LOC/Precision</PartMfg>
     <KnownMass>222.</KnownMass>
     <Density>1121.29241</Density>
     <Material>Paper</Material>
     <Name>main airframe tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>299.308234881988</CalcMass>
     <CalcCG>431.8</CalcCG>
     <WettedSurface>0.213627873215399</WettedSurface>
     <PaintedSurface>0.213627873215399</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC BT-3.00</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>5</SerialNo>
     <DisplayFlags>9</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>78.74</OD>
     <ID>76.2</ID>
     <Len>863.6</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Parachute>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>85.049</KnownMass>
       <Density>0.</Density>
       <Material>Rip stop nylon</Material>
       <Name>Parachute</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>126.4</Xb>
       <CalcMass>9.32688</CalcMass>
       <CalcCG>76.2</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LP-36</PartNo>
       <PartDesc>36 In. 10 lines</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>13</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Dia>914.4</Dia>
       <SpillHoleDia>0.</SpillHoleDia>
       <SideCount>10</SideCount>
       <ShroudLineCount>10</ShroudLineCount>
       <Thickness>5.1e-002</Thickness>
       <ShroudLineLen>914.4</ShroudLineLen>
       <ChuteCount>1</ChuteCount>
       <ShroudLineMassPerMM>1.02e-003</ShroudLineMassPerMM>
       <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
       <DragCoefficient>0.75</DragCoefficient>
       <AttachedParts>
       </AttachedParts>
      </Parachute>
      <MassObject>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1.2277353539e-002</Density>
       <Material>3/4 In. flat elastic</Material>
       <Name><![CDATA[3/4" shock cord]]></Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>287.9</Xb>
       <CalcMass>63.6163350976824</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>14</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>5181.6</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <BodyTube>
       <PartMfg>LOC/Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>motor mount tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>0.</Xb>
       <CalcMass>76.198046295897</CalcMass>
       <CalcCG>127.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC MMT-2.14</PartNo>
       <PartDesc>Motor mount tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>6</SerialNo>
       <DisplayFlags>1</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>57.404</OD>
       <ID>54.356</ID>
       <Len>254.</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>54.</MotorDia>
       <EngineOverhang>0.</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (LOC)</Material>
       <Name>forward centering ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>240.</Xb>
       <CalcMass>4.53997958762895</CalcMass>
       <CalcCG>1.5875</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-3.00-2.14</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>8</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>76.2</OD>
       <ID>57.404</ID>
       <Len>3.175</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (LOC)</Material>
       <Name>aft centering ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>10.</Xb>
       <CalcMass>4.53997958762895</CalcMass>
       <CalcCG>1.5875</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-3.00-2.14</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>11</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>76.2</OD>
       <ID>57.404</ID>
       <Len>3.175</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <FinSet>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (LOC)</Material>
       <Name>Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>645.9</Xb>
       <CalcMass>132.355265901295</CalcMass>
       <CalcCG>138.747033493481</CalcCG>
       <WettedSurface>2.145157e-002</WettedSurface>
       <PaintedSurface>8.58062800000001e-002</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>15</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>11.0139318828242</BarrowmanCNa>
       <BarrowmanXN>1.38937056845956</BarrowmanXN>
       <RockSimCNa>14.73885595858</RockSimCNa>
       <RockSimXN>1.38937056845956</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <FinCount>4</FinCount>
       <RootChord>215.9</RootChord>
       <TipChord>25.4</TipChord>
       <SemiSpan>88.9</SemiSpan>
       <MidChordLen>121.661335998949</MidChordLen>
       <SweepDistance>178.305828675952</SweepDistance>
       <Thickness>3.81</Thickness>
       <ShapeCode>0</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>1</TipShapeCode>
       <TabLength>117.475</TabLength>
       <TabDepth>10.668</TabDepth>
       <TabOffset>81.7</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>1.1082841055</SweepAngle>
       <AttachedParts>
       </AttachedParts>
      </FinSet>
     </AttachedParts>
    </BodyTube>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>738.529131230205</MaxAltitude>
   <MaxVelocity>136.038333608506</MaxVelocity>
   <MaxAcceleration>105.313885901947</MaxAcceleration>
   <TimeToApogee>11.8387500000014</TimeToApogee>
   <OptimalDelay>9.23875000000139</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.60000000000006</TimeToBurnout>
   <TimeToLanding>125.677499999904</TimeToLanding>
   <TimeToEject>12.6000000000018</TimeToEject>
   <MinLaunchGuideLen>0.933537223208201</MinLaunchGuideLen>
   <MaxVertVelocity>135.889926365659</MaxVertVelocity>
   <MaxHorzVelocity>2.71958799221917</MaxHorzVelocity>
   <MaxVertAcceleration>105.313885901947</MaxVertAcceleration>
   <MaxHorzAcceleration>0.960275296434608</MaxHorzAcceleration>
   <MaxRange>433.965651355055</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H123W-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>19.3446010100857</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.2</TimeToFreeFlight>
   <TimeToMaxVelocity>2.27250000000001</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>4.53747780793369</ExecutionTime>
   <RangeAtLanding>433.965651355055</RangeAtLanding>
   <VelocityAtLanding>6.94347069089137</VelocityAtLanding>
   <XVelcoityAtLanding>2.71960121714161</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.38870522523847</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.20159327109281</Mass0>
   <CG0>0.922286485792383</CG0>
   <LaterialMOI0>0.389065153521888</LaterialMOI0>
   <RadialMOI0>1.29389478193545e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>735.707201476813</DeployedAt_Altitude>
     <DeployedAt_Velocity>8.18366112587176</DeployedAt_Velocity>
     <DeployedAt_Range>-46.8169729390332</DeployedAt_Range>
     <DeployedAt_Time>12.6000000000018</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H123W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>1098.38202313424</MaxAltitude>
   <MaxVelocity>209.800591235579</MaxVelocity>
   <MaxAcceleration>164.927256522063</MaxAcceleration>
   <TimeToApogee>12.975000000002</TimeToApogee>
   <OptimalDelay>10.675000000002</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.30000000000001</TimeToBurnout>
   <TimeToLanding>178.631249999856</TimeToLanding>
   <TimeToEject>12.3000000000017</TimeToEject>
   <MinLaunchGuideLen>0.633784928784725</MinLaunchGuideLen>
   <MaxVertVelocity>209.514305421332</MaxVertVelocity>
   <MaxHorzVelocity>2.25756170068676</MaxHorzVelocity>
   <MaxVertAcceleration>164.927256522063</MaxVertAcceleration>
   <MaxHorzAcceleration>11.7698044312299</MaxHorzAcceleration>
   <MaxRange>471.128121087072</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I161W-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>24.6701924974011</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.20625</TimeToFreeFlight>
   <TimeToMaxVelocity>1.98874999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>8.22277216797107</ExecutionTime>
   <RangeAtLanding>471.128121087072</RangeAtLanding>
   <VelocityAtLanding>6.61861835830891</VelocityAtLanding>
   <XVelcoityAtLanding>1.37509931912913</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.47419576746597</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.29309327109281</Mass0>
   <CG0>0.951824232530263</CG0>
   <LaterialMOI0>0.39226178531463</LaterialMOI0>
   <RadialMOI0>1.85275327838475e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>1095.52212866399</DeployedAt_Altitude>
     <DeployedAt_Velocity>11.9254623626401</DeployedAt_Velocity>
     <DeployedAt_Range>-64.7844039148691</DeployedAt_Range>
     <DeployedAt_Time>12.3000000000017</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I161W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>511.507695944757</MaxAltitude>
   <MaxVelocity>121.810276159651</MaxVelocity>
   <MaxAcceleration>186.279850431288</MaxAcceleration>
   <TimeToApogee>8.36749999999967</TimeToApogee>
   <OptimalDelay>6.86624999999969</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.50124999999997</TimeToBurnout>
   <TimeToLanding>89.6399999999366</TimeToLanding>
   <TimeToEject>7.50124999999958</TimeToEject>
   <MinLaunchGuideLen>0.782974245320924</MinLaunchGuideLen>
   <MaxVertVelocity>121.63100513607</MaxVertVelocity>
   <MaxHorzVelocity>2.19927403580755</MaxHorzVelocity>
   <MaxVertAcceleration>130.839958430277</MaxVertAcceleration>
   <MaxHorzAcceleration>27.4036781086908</MaxHorzAcceleration>
   <MaxRange>264.773396788908</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H128W-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.125421570775</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.22875</TimeToFreeFlight>
   <TimeToMaxVelocity>1.34999999999998</TimeToMaxVelocity>
   <TimeToMaxAcceleration>7.50249999999958</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>3.98013490541396</ExecutionTime>
   <RangeAtLanding>264.773396788908</RangeAtLanding>
   <VelocityAtLanding>6.42743911793638</VelocityAtLanding>
   <XVelcoityAtLanding>1.49689743761233</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.25070169469384</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.12279327109281</Mass0>
   <CG0>0.881990292286054</CG0>
   <LaterialMOI0>0.378416162116025</LaterialMOI0>
   <RadialMOI0>1.34878595869353e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>505.476772526251</DeployedAt_Altitude>
     <DeployedAt_Velocity>27.2291510508278</DeployedAt_Velocity>
     <DeployedAt_Range>-29.6588775989303</DeployedAt_Range>
     <DeployedAt_Time>7.50124999999958</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H128W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>539.908411806446</MaxAltitude>
   <MaxVelocity>121.779282695382</MaxVelocity>
   <MaxAcceleration>130.839958430277</MaxAcceleration>
   <TimeToApogee>10.1600000000006</TimeToApogee>
   <OptimalDelay>8.65875000000061</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>1.50124999999997</TimeToBurnout>
   <TimeToLanding>90.322499999936</TimeToLanding>
   <TimeToEject>11.5000000000013</TimeToEject>
   <MinLaunchGuideLen>0.782974245320924</MinLaunchGuideLen>
   <MaxVertVelocity>121.502685699765</MaxVertVelocity>
   <MaxHorzVelocity>2.73874278816078</MaxHorzVelocity>
   <MaxVertAcceleration>130.839958430277</MaxVertAcceleration>
   <MaxHorzAcceleration>1.04209248511412</MaxHorzAcceleration>
   <MaxRange>315.719884500499</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H128W-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.125421570775</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.22875</TimeToFreeFlight>
   <TimeToMaxVelocity>1.34999999999998</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>5.65195911770909</ExecutionTime>
   <RangeAtLanding>315.719884500499</RangeAtLanding>
   <VelocityAtLanding>6.53400014576724</VelocityAtLanding>
   <XVelcoityAtLanding>1.90312675542399</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.25070127727087</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.12279327109281</Mass0>
   <CG0>0.881990292286054</CG0>
   <LaterialMOI0>0.378416162116025</LaterialMOI0>
   <RadialMOI0>1.34878595869353e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>531.252120173877</DeployedAt_Altitude>
     <DeployedAt_Velocity>13.610363485425</DeployedAt_Velocity>
     <DeployedAt_Range>-49.1592910651436</DeployedAt_Range>
     <DeployedAt_Time>11.5000000000013</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H128W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>811.825516212927</MaxAltitude>
   <MaxVelocity>176.422752338343</MaxVelocity>
   <MaxAcceleration>230.834449413025</MaxAcceleration>
   <TimeToApogee>11.5687500000013</TimeToApogee>
   <OptimalDelay>10.3675000000013</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.20124999999998</TimeToBurnout>
   <TimeToLanding>136.623749999894</TimeToLanding>
   <TimeToEject>11.2000000000011</TimeToEject>
   <MinLaunchGuideLen>0.415612951864105</MinLaunchGuideLen>
   <MaxVertVelocity>176.208414132656</MaxVertVelocity>
   <MaxHorzVelocity>3.53161599999256</MaxHorzVelocity>
   <MaxVertAcceleration>230.834449413025</MaxVertAcceleration>
   <MaxHorzAcceleration>5.54444638052491</MaxHorzAcceleration>
   <MaxRange>815.06329233454</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H242T-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>29.1083886816715</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.135</TimeToFreeFlight>
   <TimeToMaxVelocity>1.11874999999998</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.25e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>6.39619309158008</ExecutionTime>
   <RangeAtLanding>815.06329233454</RangeAtLanding>
   <VelocityAtLanding>7.26104973197243</VelocityAtLanding>
   <XVelcoityAtLanding>3.45069644944609</XVelcoityAtLanding>
   <YVelocityAtLanding>-6.38870387668399</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.18739327109281</Mass0>
   <CG0>0.916087392298301</CG0>
   <LaterialMOI0>0.387675797621338</LaterialMOI0>
   <RadialMOI0>1.27108685055125e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>811.085889783417</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>2565.36380402329</MaxAltitude>
   <MaxVelocity>321.2871105039</MaxVelocity>
   <MaxAcceleration>110.028766038426</MaxAcceleration>
   <TimeToApogee>19.89875</TimeToApogee>
   <OptimalDelay>12.8975000000003</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>12.2475455966475,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>2559.46989669213,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>14.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>21.001249999999,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>7.00124999999968</TimeToBurnout>
   <TimeToLanding>346.625000001763</TimeToLanding>
   <TimeToEject>21.001249999999</TimeToEject>
   <MinLaunchGuideLen>1.3183512658783</MinLaunchGuideLen>
   <MaxVertVelocity>320.856184506152</MaxVertVelocity>
   <MaxHorzVelocity>3.53161599998629</MaxHorzVelocity>
   <MaxVertAcceleration>109.85514536132</MaxVertAcceleration>
   <MaxHorzAcceleration>2.12080264138986</MaxHorzAcceleration>
   <MaxRange>1788.41508866915</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1999.49</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[J135W-14  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>16.7200006254339</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.2425</TimeToFreeFlight>
   <TimeToMaxVelocity>3.88250000000026</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.99999999999996</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>16.8741490887808</ExecutionTime>
   <RangeAtLanding>1788.41508866915</RangeAtLanding>
   <VelocityAtLanding>7.96852648792276</VelocityAtLanding>
   <XVelcoityAtLanding>2.93927611332239</XVelcoityAtLanding>
   <YVelocityAtLanding>-7.40662340870515</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,21.</StageEjectTime>
   <TimeToDeployment>0.,0.,21.001249999999</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>2.03399327109281</Mass0>
   <CG0>1.08682763446915</CG0>
   <LaterialMOI0>0.417861362786482</LaterialMOI0>
   <RadialMOI0>8.59097912517025e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>2559.46989669213</DeployedAt_Altitude>
     <DeployedAt_Velocity>12.2475455966475</DeployedAt_Velocity>
     <DeployedAt_Range>-174.665639170129</DeployedAt_Range>
     <DeployedAt_Time>21.001249999999</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>J135W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>14.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>1103.21343946714</MaxAltitude>
   <MaxVelocity>209.823012550316</MaxVelocity>
   <MaxAcceleration>164.927256522063</MaxAcceleration>
   <TimeToApogee>13.4262500000023</TimeToApogee>
   <OptimalDelay>11.1262500000022</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>25.9974908216172,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>1064.73662599685,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>14.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>16.3000000000033,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.30000000000001</TimeToBurnout>
   <TimeToLanding>192.516249999843</TimeToLanding>
   <TimeToEject>16.3000000000033</TimeToEject>
   <MinLaunchGuideLen>0.633784928784725</MinLaunchGuideLen>
   <MaxVertVelocity>209.717191191038</MaxVertVelocity>
   <MaxHorzVelocity>3.20782565705274</MaxHorzVelocity>
   <MaxVertAcceleration>164.927256522063</MaxVertAcceleration>
   <MaxHorzAcceleration>1.43356568105048</MaxHorzAcceleration>
   <MaxRange>776.301601448898</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>1999.49</LaunchGuideLen>
   <LaunchBarometer>760.</LaunchBarometer>
   <LaunchLatitude>0.580008</LaunchLatitude>
   <LaunchHumidity>25.</LaunchHumidity>
   <LaunchTemperature>15.</LaunchTemperature>
   <LaunchAltitude>914.4</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>3</LaunchWindPreset>
   <LaunchWindLowSpeed>1.34112</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>3.531616</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
   <LaunchCCLow>0.</LaunchCCLow>
   <LaunchCCHigh>0.1</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I161W-14  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>24.6701924974011</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.99949</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.20625</TimeToFreeFlight>
   <TimeToMaxVelocity>1.98874999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
   <SamplesPerSecond>800</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>12.29711122503</ExecutionTime>
   <RangeAtLanding>776.301601448898</RangeAtLanding>
   <VelocityAtLanding>5.04778365074371</VelocityAtLanding>
   <XVelcoityAtLanding>3.20783537505928</XVelcoityAtLanding>
   <YVelocityAtLanding>-3.89742376336392</YVelocityAtLanding>
   <StageEjectTime>-1.,-1.,16.3</StageEjectTime>
   <TimeToDeployment>0.,0.,16.3000000000033</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>1</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>1.29309327109281</Mass0>
   <CG0>0.951824232530263</CG0>
   <LaterialMOI0>0.39226178531463</LaterialMOI0>
   <RadialMOI0>1.85275327838475e-003</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>13</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>1064.73662599685</DeployedAt_Altitude>
     <DeployedAt_Velocity>25.9974908216172</DeployedAt_Velocity>
     <DeployedAt_Range>-48.7718180650661</DeployedAt_Range>
     <DeployedAt_Time>16.3000000000033</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I161W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>6</MountSerialNo>
     <EjectionDelay>14.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
